### ISSUE TITLE
Checklist of feature requests for flatbuffers

### ISSUE THREAD

**Issue by TethysSvensson** [fitzgen/bumpalo#38]
~~With #37 implemented, I think bumpalo is much closer to being a possible backend for flatbuffers. However there are still a few features that would be needed, some of which might require guarantees that bumpalo is unable to provide.~~

~~I am hoping we can use this issue to discuss whether this sounds realistic or not. To use bumpalo, we would need:~~

- [ ] ~~Knowledge of the total number of bytes allocated so far. Either through an `allocated_bytes()` method on the Bump, or through a method that returns both a pointer and the actual number of bytes allocated.~~
- [ ] ~~Control over the padding bytes to avoid UB and leaking previous bytes in the buffer. Perhaps a method that guarantees that the padding has been zeroed? Perhaps if we had a method `fn alloc_padding(&self, align: usize) -> &mut [u8]` which gives a slice with `0 <= len < align`?~~
- [ ] ~~Guarantees about allocation strategy. With #37, the allocation strategy was changed. Would it be possible to guarantee that it will not change again? Perhaps a guarantee that allocations will always happen from the back if a specific feature flag is set?~~
- [ ] ~~Bonus: Reverse iterator. Currently the allocated chunks are enumerated oldest-to-newest, but we would like to have a method for doing newest-to-oldest. (Though collecting them and reversing is not too much trouble either).~~

~~What do you think? Does it make sense to continue pursuing this?~~

See later post.

**Comment by TethysSvensson** [comment]
There is also an issue with how alignment might change between chunks, because flatbuffers also has alignment requirements in it's file format.

Consider this example:

```rust
// In chunk1, written last
bump.alloc(NeedsAlignment4 { ... });
bump.alloc(42u8);

// In chunk 2, written first
bump.alloc(NeedsAlignment4 { ... });
```

If I then used `iter_allocated_chunks()` and wrote all the bytes to disk, I would find that the first object was not actually aligned anymore. To be useful to flatbuffers I think more generally we would require that the following code example would always work:

```rust
let ptr = bump.alloc(some_valid_layout());
assert_eq!((ptr as usize) % 8, bump.total_allocated_bytes() % 8);
```

I think I am slowly reaching the conclusion, that this is putting too many requirements on bumpalo. While bumpalo would probably be very useful for flatbuffers, if suitable tweaked, am afraid whether such tweaking would be detrimental to other users of bumpalo.

**Comment by TethysSvensson** [comment]
Actually, if we just care about alignment of the output and not in-memory alignment this becomes a lot simpler. That way we can always just call `fn alloc_layout(Layout::from_size_align_unchecked(n, 1))`.

In that case most of the above goes away. We would only need:

- [ ] Guarantees about allocating from the back
- [ ] Bonus: An iterator that gives the newest allocated chunks first.

**Comment by fitzgen** [comment]
* Yes, I will guarantee that allocation direction will not change without a breaking version bump (I plan to do a breaking bump for the most recent changes). I can document this in the API docs as well.

* The iterator would require changes to the way that the chunks are held together, since it is a singly linked list right now. Is collect + reverse a deal breaker?

**Comment by TethysSvensson** [comment]
I would be surprised if it was a deal break. I however do think that the current behavior is less intuitive, less likely to be useful for most users and harder to implement than the alternative.

**Intuitiveness**
The old implement was very easy to explain, without ever going into details about the allocation strategy. "The first byte you get is the first byte of the first allocation, and the become newer after that".

To explain the current version without talking explicitly about allocation strategy, you need something along the lines of "Bytes are returned in chunks, and these are ordered by age with the oldest first. Internally in a chunk, allocations are ordered newer to older."

The explanation of the the alternative could simply be "The first byte you get is the first byte of the most recent allocation, and they become older after that."

**Usability**
I think the most likely operations users of the `iter_each_chunk` API are likely to want to do are the following (in a random order):
* Concatenate all the bytes, oldest first
* Concatenate all the bytes, newest first
* Find the bytes used in the oldest allocation
* Find the bytes used in the newest allocation
* Figure out how many bytes have been allocated in total
* Figure out how many times a specific pattern occurs

I think all of these points would be as easy or easier with the alternative strategy.

**Implementation difficulty**
I think it would make the implementation simpler and possibly more performant if you used a singly linked list in the opposite direction. This would mean that a `Bump` would just be a single pointer instead of two.

**Comment by fitzgen** [comment]
My main use case is in Dodrio, where we allocate instructions into the bump arena, and then iterate over them in order of allocation (details [here](https://hacks.mozilla.org/2019/03/fast-bump-allocated-virtual-doms-with-rust-and-wasm/), if you want them). The direction within a chunk doesn't matter because it is easy to change a `for` loop to go either way in this case, but getting the chunks themselves in order of allocation is important since it means we don't need to collect and reverse in our frame rendering critical path.

**Comment by TethysSvensson** [comment]
I hadn't really looked at dodrio before. It looks really neat! 

If I understand your plan correctly, then your plan is to use the new allocation strategy, and then change e.g. `op2`, so that it becomes

```rust
fn op2(&self, discriminant: ChangeDiscriminant, a: u32, b: u32) {
    self.bump.alloc([b, a, discriminant as u32]);
}
```

Then you will pass all of the allocated words to javascript and have javascript interpret them with the oldest word being interpreted first. Is my understanding correct?

As far as I can tell, you would still be able to do this if you changed the order of the returned chunks. Couldn't you just reverse the loop in the javascript interpreter here:

https://github.com/fitzgen/dodrio/blob/83d5581900d20dafa20a4d365282fb9c0a0ed00c/js/change-list-interpreter.js#L320

Or do you think that would have a negative performance impact because of the JIT compiler being unable to optimize it?

In any case, I think I get your point and can see why this might be detrimental to your use case.

I am still of the opinion that the alternative API is more intuitive, and would work better for most users. However given that one of your most important users (i.e. yourself) disagree with my assertion, who am I to argue with that. :wink:

There are a few use cases in flatbuffers where the extra allocation of a Vec might matter, but those cases are not supported well currently either.

One of these use cases are users on embedded platforms with a custom heap implementation. These users might be happy to e.g. have the guarantee that flatbuffer will only every request memory in multiples of *X* or that flatbuffer will request memory from the heap exactly once unless you try to serialize messages larger than *Y*.

No matter what you decide, I am hugely grateful for the amount of work you have put into bumpalo. If I ever bump into you (pun intended), I'll definitely by you a cup of coffee. :smile:

**Comment by fitzgen** [comment]
> If I understand your plan correctly, then your plan is to use the new allocation strategy, and then change e.g. `op2`, so that it becomes

Correct.

> Couldn't you just reverse the loop in the javascript interpreter here:
> 
> https://github.com/fitzgen/dodrio/blob/83d5581900d20dafa20a4d365282fb9c0a0ed00c/js/change-list-interpreter.js#L320

Oh good eye! I didn't realize I was already collecting all the ranges in a JS array, in which case it is as easy to reverse the `for` loop iteration of chunks as it is to reverse it within a chunk.

My fears were unfounded, so if you want to make a PR to reverse the direction of the singly-linked list so it is most-recently allocated chunk to least-recently allocated chunk, and make `Bump` only keep track of the head of the list, please be my guest :)

**Comment by TethysSvensson** [comment]
This was solved in #42.
